### ISSUE TITLE
Feature: User can search for public holidays by country

### ISSUE THREAD

**Issue by kakriske** [kakriske/ajax-project1#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="421" alt="Screenshot 2023-11-27 at 10 58 36 AM" src="https://github.com/kakriske/ajax-project1/assets/142456210/1862e12b-3007-4bcb-a716-05ec8d7ab977">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [x] Fix HTML/CSS to match wireframe and be desktop and mobile responsive.
- [x] Create a select input box for user to select by country.
- [x]  Capture value chosen upon form submission.
- [x] Make an Ajax request to 'https://date.nager.at/api/v3/NextPublicHolidays-with country code
- [x] Set up the list of country codes
- [x]  Create some sort of DOM creation function - to create an li, with the name of the holiday.
- [x] Populate a ul with those li's.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
